#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
医学论文笔记生成器
整合 evil-read-arxiv 的笔记生成功能，适配医学文献格式

功能：
1. 生成符合Obsidian格式的结构化笔记
2. 支持中英文输出
3. 包含医学专业字段（PMID、MeSH术语等）
4. 自动生成研究价值评估
5. 可选的自动摘要翻译（使用 Claude API 或自定义 LLM API）
"""

import os
import sys
import re
import logging
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional, Any

# 添加脚本目录到路径
SCRIPT_DIR = Path(__file__).parent
sys.path.insert(0, str(SCRIPT_DIR))

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# ============================================================================
# 用户配置区
# ============================================================================
NOTE_TEMPLATE_ZH = '''---
date: "{date}"
pmid: "{pmid}"
doi: "{doi}"
title: "{title}"
authors: "{authors}"
journal: "{journal}"
year: {year}
domain: "{domain}"
tags:
  - 论文笔记
  - {domain}
sources:
{sources_yaml}
priority_score: {priority_score}
mesh_terms:
{mesh_yaml}
created: "{date}"
updated: "{date}"
status: to_read
---

# {title}

## 核心信息

- **PMID**: {pmid_link}
- **DOI**: {doi_link}
- **期刊**: {journal} ({year})
- **作者**: {authors}
- **数据源**: {sources}
- **优先级评分**: {priority_score}/100

## 摘要

{abstract}

## 摘要翻译

[待补充：中文翻译]

**翻译建议**：
1. 使用 Claude 或其他 AI 工具翻译上述英文摘要
2. 翻译时注意：
   - 保持医学术语的准确性（如 dementia → 痴呆症，而非失智症）
   - 保留专业名词的英文原文（如 RCT、MeSH等）
   - 适当调整语序以符合中文学术表达习惯
   - 保持原文的逻辑结构（背景-方法-结果-结论）

**快速翻译提示词**：
```
请将以下医学论文摘要翻译成中文，要求：
1. 保持医学术语的准确性和规范性
2. 保留关键专业名词的英文原文（如研究方法、统计指标等）
3. 使用学术化的中文表达
4. 保持原文的逻辑结构

摘要：
{abstract}
```

## 研究背景与动机

[待补充：研究背景]

## 研究问题

[待补充：核心研究问题]

## 方法概述

### 研究设计

[待补充：研究类型、设计]

### 数据来源

[待补充：数据集、样本]

### 分析方法

[待补充：统计方法、模型]

## 主要发现

### 核心结果

[待补充：主要结果]

### 关键数据

[待补充：关键统计数据]

## 研究价值评估

### 理论贡献

[待补充：对理论发展的贡献]

### 实践意义

[待补充：对临床实践/政策制定的启示]

### 方法创新

[待补充：方法学创新点]

## 优势与局限

### 研究优势

1. [优势1]
2. [优势2]

### 研究局限

1. [局限1]
2. [局限2]

## 相关论文

- [[相关论文1]]
- [[相关论文2]]

## 个人笔记

[待补充：个人思考、启发、应用设想]

## 参考文献

{references}

---
*本笔记由 med-start-my-day 自动生成*
'''

NOTE_TEMPLATE_EN = '''---
date: "{date}"
pmid: "{pmid}"
doi: "{doi}"
title: "{title}"
authors: "{authors}"
journal: "{journal}"
year: {year}
domain: "{domain}"
tags:
  - paper-notes
  - {domain}
sources:
{sources_yaml}
priority_score: {priority_score}
mesh_terms:
{mesh_yaml}
created: "{date}"
updated: "{date}"
status: to_read
---

# {title}

## Core Information

- **PMID**: {pmid_link}
- **DOI**: {doi_link}
- **Journal**: {journal} ({year})
- **Authors**: {authors}
- **Data Sources**: {sources}
- **Priority Score**: {priority_score}/100

## Abstract

{abstract}

## Research Background

[To be added]

## Research Question

[To be added]

## Methods

### Study Design

[To be added]

### Data Sources

[To be added]

### Analysis Methods

[To be added]

## Key Findings

### Main Results

[To be added]

### Key Data

[To be added]

## Research Value

### Theoretical Contribution

[To be added]

### Practical Implications

[To be added]

### Methodological Innovation

[To be added]

## Strengths and Limitations

### Strengths

1. [Strength 1]
2. [Strength 2]

### Limitations

1. [Limitation 1]
2. [Limitation 2]

## Related Papers

- [[Related Paper 1]]
- [[Related Paper 2]]

## Personal Notes

[To be added]

## References

{references}

---
*Generated by med-start-my-day*
'''


def get_vault_path(cli_vault: str = None) -> str:
    """
    获取Obsidian Vault路径
    
    优先级：
    1. CLI参数
    2. 环境变量 OBSIDIAN_VAULT_PATH
    """
    if cli_vault:
        return cli_vault
    
    env_path = os.environ.get('OBSIDIAN_VAULT_PATH')
    if env_path:
        return env_path
    
    logger.error("未指定vault路径。请通过 --vault 参数或 OBSIDIAN_VAULT_PATH 环境变量设置。")
    sys.exit(1)


def sanitize_filename(title: str) -> str:
    """
    清理文件名，移除非法字符
    
    参数：
        title: 原始标题
    
    返回：
        合法的文件名
    """
    # 移除Windows文件名非法字符
    illegal_chars = r'[<>:"/\\|?*]'
    clean = re.sub(illegal_chars, '', title)
    # 限制长度
    if len(clean) > 100:
        clean = clean[:100]
    return clean.strip()


def generate_note(
    paper_data: Dict,
    vault_path: str,
    domain: str = "",
    language: str = "zh",
    overwrite: bool = False,
    auto_translate: bool = False,
    translation_api: str = "claude",
    translation_api_url: Optional[str] = None,
    translation_api_key: Optional[str] = None
) -> str:
    """
    生成论文笔记

    参数：
        paper_data: 论文数据字典
        vault_path: Obsidian Vault路径
        domain: 研究领域
        language: 语言（zh/en）
        overwrite: 是否覆盖已有文件
        auto_translate: 是否自动翻译摘要
        translation_api: 翻译API类型（claude/custom）
        translation_api_url: 自定义API URL
        translation_api_key: API Key

    返回：
        生成的笔记文件路径
    """
    # 确定保存目录
    papers_dir = Path(vault_path) / "20_Research" / "Papers"
    domain_dir = papers_dir / domain if domain else papers_dir
    domain_dir.mkdir(parents=True, exist_ok=True)
    
    # 生成文件名
    title = paper_data.get('title', 'Unknown Title')
    filename = sanitize_filename(title) + ".md"
    filepath = domain_dir / filename
    
    # 检查是否已存在
    if filepath.exists() and not overwrite:
        logger.info(f"笔记已存在: {filepath}")
        return str(filepath)
    
    # 准备模板变量
    template = NOTE_TEMPLATE_ZH if language == "zh" else NOTE_TEMPLATE_EN
    
    # 格式化作者
    authors = paper_data.get('authors', [])
    if isinstance(authors, list):
        if len(authors) > 3:
            authors_str = f"{authors[0]} et al."
        else:
            authors_str = ', '.join(authors)
    else:
        authors_str = str(authors)
    
    # 格式化来源
    sources = paper_data.get('source_apis', [])
    sources_str = ', '.join(sources) if sources else 'Unknown'
    sources_yaml = '\n'.join(f'  - {s}' for s in sources) if sources else '  - unknown'
    
    # 格式化MeSH术语
    mesh_terms = paper_data.get('mesh_terms', [])
    mesh_yaml = '\n'.join(f'  - {m}' for m in mesh_terms) if mesh_terms else '  - []'
    
    # 构建链接
    pmid = paper_data.get('pmid', '')
    doi = paper_data.get('doi', '')
    
    pmid_link = f"[{pmid}](https://pubmed.ncbi.nlm.nih.gov/{pmid}/)" if pmid else "N/A"
    doi_link = f"[{doi}](https://doi.org/{doi})" if doi else "N/A"
    
    # 处理摘要
    abstract = paper_data.get('abstract', '')
    if abstract and len(abstract) > 2000:
        abstract = abstract[:2000] + "..."
    
    # 当前日期
    today = datetime.now().strftime('%Y-%m-%d')
    
    # 填充模板
    note_content = template.format(
        date=today,
        pmid=pmid or "N/A",
        doi=doi or "N/A",
        title=title,
        authors=authors_str,
        journal=paper_data.get('journal', 'Unknown Journal'),
        year=paper_data.get('year', 'Unknown'),
        domain=domain or "General",
        sources_yaml=sources_yaml,
        sources=sources_str,
        priority_score=paper_data.get('priority_score', 0),
        mesh_yaml=mesh_yaml,
        pmid_link=pmid_link,
        doi_link=doi_link,
        abstract=abstract or "[摘要不可用]",
        references=""
    )
    
    # 写入文件
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(note_content)

    logger.info(f"生成笔记: {filepath}")

    # 自动翻译摘要
    if auto_translate and abstract and abstract != "[摘要不可用]":
        logger.info("正在翻译摘要...")
        try:
            from translate_abstract import translate_note_abstract

            success = translate_note_abstract(
                note_path=str(filepath),
                api_type=translation_api,
                api_url=translation_api_url,
                api_key=translation_api_key
            )

            if success:
                logger.info("摘要翻译完成")
            else:
                logger.warning("摘要翻译失败，请手动翻译")
        except Exception as e:
            logger.error(f"翻译过程出错: {e}")
            logger.warning("将保留翻译提示，请手动翻译")

    return str(filepath)


def generate_daily_summary(
    papers: List[Dict],
    vault_path: str,
    queries: List[Dict],
    language: str = "zh"
) -> str:
    """
    生成每日推荐摘要
    
    参数：
        papers: 论文列表
        vault_path: Obsidian Vault路径
        queries: 检索查询列表
        language: 语言
    
    返回：
        摘要文件路径
    """
    # 确定保存目录
    daily_dir = Path(vault_path) / "10_Daily"
    daily_dir.mkdir(parents=True, exist_ok=True)
    
    # 生成文件名
    today = datetime.now()
    filename = today.strftime('%Y-%m-%d') + "-文献推荐.md"
    filepath = daily_dir / filename
    
    # 构建摘要内容
    lines = []
    
    # 标题
    if language == "zh":
        lines.append(f"# 📚 每日文献推荐 - {today.strftime('%Y年%m月%d日')}")
    else:
        lines.append(f"# 📚 Daily Literature Recommendations - {today.strftime('%Y-%m-%d')}")
    
    lines.append("")
    
    # 检索概览
    if language == "zh":
        lines.append("## 检索概览")
        lines.append("")
        lines.append(f"- **检索时间**: {today.strftime('%Y-%m-%d %H:%M')}")
        lines.append(f"- **检索领域**: {len(queries)} 个")
        lines.append(f"- **总结果数**: {len(papers)} 篇")
        lines.append(f"- **数据源**: PubMed, Semantic Scholar, OpenAlex")
    else:
        lines.append("## Search Overview")
        lines.append("")
        lines.append(f"- **Search Time**: {today.strftime('%Y-%m-%d %H:%M')}")
        lines.append(f"- **Domains**: {len(queries)}")
        lines.append(f"- **Total Results**: {len(papers)} papers")
        lines.append(f"- **Data Sources**: PubMed, Semantic Scholar, OpenAlex")
    
    lines.append("")
    lines.append("---")
    lines.append("")
    
    # 检索查询详情
    if language == "zh":
        lines.append("## 检索详情")
    else:
        lines.append("## Search Details")
    
    lines.append("")
    
    for i, q in enumerate(queries, 1):
        domain = q.get('domain', 'Unknown')
        query = q.get('query', '')
        count = q.get('count', 0)
        
        if language == "zh":
            lines.append(f"### {i}. {domain}")
        else:
            lines.append(f"### {i}. {domain}")
        
        lines.append(f"- **查询**: `{query}`")
        lines.append(f"- **结果数**: {count}")
        lines.append("")
    
    lines.append("---")
    lines.append("")
    
    # 推荐论文列表
    if language == "zh":
        lines.append("## 推荐论文")
    else:
        lines.append("## Recommended Papers")
    
    lines.append("")
    
    for i, paper in enumerate(papers[:20], 1):  # 最多显示20篇
        title = paper.get('title', 'Unknown Title')
        authors = paper.get('authors', [])
        if isinstance(authors, list) and len(authors) > 0:
            author_str = authors[0] if len(authors) == 1 else f"{authors[0]} et al."
        else:
            author_str = "Unknown"
        
        journal = paper.get('journal', 'Unknown Journal')
        year = paper.get('year', 'Unknown')
        pmid = paper.get('pmid', '')
        doi = paper.get('doi', '')
        priority = paper.get('priority_score', 0)
        sources = ', '.join(paper.get('source_apis', []))
        
        # 论文条目
        lines.append(f"### {i}. {title}")
        lines.append("")
        lines.append(f"- **作者**: {author_str}")
        lines.append(f"- **期刊**: {journal} ({year})")
        
        if pmid:
            lines.append(f"- **PMID**: [{pmid}](https://pubmed.ncbi.nlm.nih.gov/{pmid}/)")
        if doi:
            lines.append(f"- **DOI**: [{doi}](https://doi.org/{doi})")
        
        lines.append(f"- **数据源**: {sources}")
        lines.append(f"- **优先级**: {priority}")
        lines.append("")
        
        # 摘要预览
        abstract = paper.get('abstract', '')
        if abstract:
            preview = abstract[:300] + "..." if len(abstract) > 300 else abstract
            lines.append(f"> {preview}")
            lines.append("")
        
        lines.append("---")
        lines.append("")
    
    # 写入文件
    content = '\n'.join(lines)
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)
    
    logger.info(f"生成每日摘要: {filepath}")
    
    return str(filepath)


# ============================================================================
# 测试
# ============================================================================
if __name__ == "__main__":
    # 测试数据
    test_paper = {
        'title': 'Dementia care in primary care settings: a systematic review',
        'authors': ['Smith J', 'Johnson A', 'Williams B'],
        'journal': 'Journal of Primary Care',
        'year': 2024,
        'pmid': '12345678',
        'doi': '10.1234/test.2024',
        'abstract': 'This is a test abstract for the paper...',
        'source_apis': ['pubmed', 'semantic_scholar'],
        'priority_score': 95,
        'mesh_terms': ['Dementia', 'Primary Health Care']
    }
    
    # 测试笔记生成
    vault = os.environ.get('OBSIDIAN_VAULT_PATH', './test_vault')
    
    print("测试笔记生成...")
    note_path = generate_note(test_paper, vault, domain="痴呆症照护", language="zh")
    print(f"生成笔记: {note_path}")
    
    # 测试每日摘要
    print("\n测试每日摘要...")
    papers = [test_paper] * 5
    queries = [
        {'domain': '痴呆症照护', 'query': 'dementia care primary care', 'count': 5}
    ]
    
    summary_path = generate_daily_summary(papers, vault, queries, language="zh")
    print(f"生成摘要: {summary_path}")
